export const SERVER_GET_CAKES_REQUEST = 'SERVER_GET_CAKES_REQUEST';
export const SERVER_GET_CAKES_SUCCESS = 'SERVER_GET_CAKES_SUCCESS';
export const SERVER_GET_CAKE_REQUEST = 'SERVER_GET_CAKE_REQUEST';
export const SERVER_GET_CAKE_SUCCESS = 'SERVER_GET_CAKE_SUCCESS';
export const SERVER_GET_CAKE_INVALID = 'SERVER_GET_CAKE_INVALID';
export const SERVER_ERROR = 'SERVER_ERROR';